language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: "./gradlew clean build"

before_deploy:
    - export PLUGIN_DIST=$(ls rest-runner-server/build/distributions/rest-runner-teamcity-plugin*.zip)

deploy:
  provider: releases
  api_key:
    secure: kxqFbpBOiKAZoZ0iq4LIL/gNJM4ijEgRLfLa4tOwzPVknI2UJG6zOQ7Z+DFchNJNy6jLLEiHPndtiC+cauMCal7oyiHb2twkLOO/37koEGQWObQX5QpVhnU6o4tVcWiYr8N0fwQdHYj7j1AXMjpThRRg+DNpxKQI7XnYsI6OtynwEt8rDw/r+k3HF0Mu5p/4DFKtTmW39O7pFPiuycUFhmUCqzkfy3dlD6jN+7lfKgcZNVW92N57QhobF/Zj1372F/CfJvmrGvctmvXw7dLux/RlOJed6RvhPrX/2MLBWkFLHZoW5CP+bqwEqV2+MnNdmRsz+BGb66Urrp+v6nfowBsh/C5Vaint7KpEjhbd8qUXD6L1+nW6mhGYTUfJZf9/fLbhK77slkMblsvZ8qHoUkwbOiAQhpeao1E2O4H/lMSdvgj/TuBZbyPKdL6BAYaoF+HWa9MFnYMSLH1okrbMWpPsz6TVcwe7dSP24CsZA+TrZlj5Zl4o0GMTAiMjpezrGOOh0h9I1tu+3xLxNe1q+lLztygA3qVrRJAM4bBgBWrFkKrroAI6WFJ7rBM0tnon8Q86nepPuYj1hppyD+OnecRzXtXXNlrpNK/aroSDYeMP+kQEE08nlKTrn++6GNFP1MMfdQ4HZSeV5ZNMp8TWZQj6nRJmZxfUo2QS5QCqpj8=
  file_glob: true
  file: ${PLUGIN_DIST}
  skip_cleanup: true
  on:
    repo: dmitry-zhuravlev/rest-runner-teamcity-plugin
    tags: true